#!/bin/sh

sudo apt-get -y install \
  ack \
  cmake \
  coreutils \
  ctags \
  erlang \
  gawk \
  git \
  gnupg \
  gnuplot \
  ifstat \
  iftop \
  jasper \
  lame \
  markdown \
  mtr \
  nmap \
  openvpn \
  pv \
  runit \
  sbcl \
  socat \
  ssldump \
  tcpflow \
  tmux \
  tree \
  unrar \
  watch \
  wget \
  x264 \
  yasm \
  zsh
